---
- name: Installing ZSH on Debian/Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Installing ZSH on Arch Linux
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
