---
- name: Nerd Fonts | Definir variables base para la instalación
  ansible.builtin.set_fact:
    fact_font_name: "{{ nerd_font_name | default('JetBrainsMono') }}"
    fact_font_version: "{{ nerd_font_version | default('v3.2.1') }}"
  when: ansible_distribution == "Ubuntu"

- name: Nerd Fonts | Definir rutas y URLs de descarga
  ansible.builtin.set_fact:
    fact_user_fonts_dir: "{{ user_home }}/.local/share/fonts"
    fact_font_download_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fact_font_version }}/{{ fact_font_name }}.zip"
    fact_font_temp_download_path: "/tmp/{{ fact_font_name }}.zip"
  when: ansible_distribution == "Ubuntu"

- name: Nerd Fonts | Instalar prerequisitos (wget, unzip, fontconfig) en Ubuntu
  ansible.builtin.apt:
    name:
      - wget
      - unzip
      - fontconfig
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Nerd Fonts | Crear directorio de fuentes del usuario si no existe
  ansible.builtin.file:
    path: "{{ fact_user_fonts_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  when: ansible_distribution == "Ubuntu"

- name: Nerd Fonts | Descargar el archivo ZIP de la Nerd Font seleccionada
  ansible.builtin.get_url:
    url: "{{ fact_font_download_url }}"
    dest: "{{ fact_font_temp_download_path }}"
    mode: "0644"
  when: ansible_distribution == "Ubuntu"
  register: nerd_font_downloaded

- name: Nerd Fonts | Descomprimir la Nerd Font en el directorio de fuentes del usuario
  ansible.builtin.unarchive:
    src: "{{ fact_font_temp_download_path }}"
    dest: "{{ fact_user_fonts_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    remote_src: yes
    creates: "{{ fact_user_fonts_dir }}/{{ fact_font_name | replace(' ', '') }}NerdFont-Regular.ttf" # [2]
  when:
    - ansible_distribution == "Ubuntu"
    - nerd_font_downloaded.changed
  register: nerd_font_unarchive_result

- name: Nerd Fonts | Limpiar archivo ZIP descargado
  ansible.builtin.file:
    path: "{{ fact_font_temp_download_path }}"
    state: absent
  when:
    - ansible_distribution == "Ubuntu"
    - nerd_font_downloaded.changed

- name: Nerd Fonts | Actualizar la caché de fuentes del sistema
  ansible.builtin.command: "fc-cache -fv"
  when:
    - ansible_distribution == "Ubuntu"
    - nerd_font_unarchive_result.changed
  changed_when: false
  become: true
