---
- name: Zoxide | Instalar curl (prerrequisito para el script de instalación de zoxide)
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes # Solo si es la primera tarea apt en mucho tiempo
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Zoxide | Instalar zoxide usando el script oficial
  ansible.builtin.shell:
    cmd: "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
    executable: /bin/bash # O /bin/sh
  args:
    # El script de instalación de zoxide generalmente instala en ~/.local/bin/zoxide
    # y las manpages en ~/.local/share/man/man1/zoxide.1.
    # Esta comprobación 'creates' ayuda con la idempotencia.
    creates: "{{ user_home }}/.local/bin/zoxide"
  environment:
    # El script de instalación puede usar HOME para determinar dónde instalar.
    # Si 'become: true' es global y no hay 'become_user', HOME podría ser /root.
    # Forzar HOME al del usuario objetivo si la tarea se ejecuta con 'become: true' sin 'become_user'.
    HOME: "{{ user_home }}"
    # PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin" # Opcional, para que sh encuentre comandos
  when: ansible_distribution == "Ubuntu"
  # Si 'become: true' es global en el playbook:
  # El script de zoxide está diseñado para instalarse en el directorio del usuario ($HOME/.local/bin)
  # por lo que 'become: true' podría no ser estrictamente necesario si se ejecuta como el usuario.
  # Sin embargo, si la tarea se ejecuta como root debido a un 'become: true' global
  # sin 'become_user', es CRUCIAL que la variable HOME esté correctamente seteada
  # para que la instalación ocurra en el home del usuario correcto y no en /root/.local/bin.
  # Si la tarea usa 'become: true' y 'become_user: "{{ user_name }}"', entonces HOME se resolvería correctamente.
  # Por simplicidad y asumiendo un 'become: true' global, establecer HOME aquí es una buena salvaguarda.
  become: true # Necesario si el 'sh' necesita escribir en directorios protegidos o si HOME no se establece correctamente
  become_user: "{{ user_name }}" # ¡MUY RECOMENDADO para que se instale en el home del usuario correcto!
  register: zoxide_install_script_result
  changed_when: "'Installed zoxide to' in zoxide_install_script_result.stdout" # El script indica si instaló

- name: Zoxide | Mostrar resultado de la instalación (debug)
  ansible.builtin.debug:
    var: zoxide_install_script_result
  when:
    - ansible_distribution == "Ubuntu"
    - zoxide_install_script_result is defined
    - zoxide_install_script_result.changed # Solo mostrar si algo cambió

# La inicialización de zoxide se añade al final de config.fish
# Esto se maneja mejor directamente en el archivo config.fish
# o con una tarea 'blockinfile' si quieres gestionarlo por separado.
# Por ahora, asumimos que se añadirá manualmente o mediante la actualización de tu
# archivo 'ansible/files/config.fish' como se muestra abajo.
