---
- name: Neovim | Remove folder if exists
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Neovim | Install Dependencies
  block:
  - name: Install ninja-build
    ansible.builtin.apt:
      name: ninja-build
      state: present
  - name: Neovim | Install gettext
    ansible.builtin.apt:
      name: gettext
      state: present
  - name: Neovim | Install cmake
    ansible.builtin.apt:
      name: cmake
      state: present
  - name: Neovim | Install unzip
    ansible.builtin.apt:
      name: unzip
      state: present
  - name: Neovim | Install curl
    ansible.builtin.apt:
      name: curl
      state: present
- name: Neovim | Clone Repository
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ user_home }}/neovim"
  tags:
    - install
    - neovim
- name: Neovim | Build from source
  shell: "cd {{ user_home }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim
- name: Neovim | Install
  shell: "cd {{ user_home }}/neovim && make install"
  tags:
    - install
    - neovim
