---
- name: Neovim | Instalar Dependencias (Ubuntu)
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
      - pkg-config
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - unzip
    state: present
    update_cache: yes
  become: true

- name: Neovim | Clonar o actualizar el repositorio de Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ user_home }}/neovim"
    version: master
    update: yes
  become: yes
  become_user: "{{ user_name }}"
  register: neovim_git_clone

- name: Neovim | Compilar Neovim desde la fuente
  ansible.builtin.command: make CMAKE_BUILD_TYPE=RelWithDebInfo
  args:
    chdir: "{{ user_home }}/neovim"
    creates: "{{ user_home }}/neovim/build/bin/nvim"
  become: yes
  become_user: "{{ user_name }}"
  register: neovim_build_result

- name: Neovim | Instalar Neovim
  ansible.builtin.command: make install
  args:
    chdir: "{{ user_home }}/neovim"
    creates: "/usr/local/bin/nvim"
  when: neovim_build_result.changed
  become: true
