---
- name: Eza | Instalar prerequisitos para eza (gpg, apt-transport-https) en Ubuntu
  ansible.builtin.apt:
    name:
      - gpg
      - apt-transport-https
    state: present
    update_cache: yes # Actualiza una vez aquí al inicio
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado

- name: Eza | Crear directorio para llaveros de APT si no existe en Ubuntu
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado

- name: Eza | Añadir clave GPG del repositorio de eza en Ubuntu
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc"
    dest: "/etc/apt/keyrings/eza-archive-keyring.asc"
    mode: "0644"
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado
  register: eza_gpg_key_added

- name: Eza | Añadir repositorio de eza en Ubuntu
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/eza-archive-keyring.asc] https://deb.hzuccon.com/ ./"
    state: present
    filename: eza
    # update_cache: yes # Quitar de aquí temporalmente
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado
  register: eza_repo_added

# Tarea explícita para actualizar la caché después de cambios en repos/claves
- name: Eza | Actualizar caché de APT después de añadir repo/clave de eza
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and (eza_gpg_key_added.changed or eza_repo_added.changed)
  # 'become: true' heredado

- name: Eza | Instalar eza en Ubuntu
  ansible.builtin.apt:
    name: eza
    state: present
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado
  register: eza_install_status

- name: Eza | Mostrar estado de la instalación (debug)
  ansible.builtin.debug:
    var: eza_install_status
  when: ansible_distribution == "Ubuntu"
