---
- name: Eza | Instalar prerequisitos para eza (gpg, apt-transport-https) en Ubuntu
  ansible.builtin.apt:
    name:
      - gpg
      - apt-transport-https # Buena práctica para repositorios HTTPS, aunque el de eza es HTTP
    state: present
    update_cache: yes # Actualiza una vez aquí al inicio, antes de manipular repositorios
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado del playbook principal

- name: Eza | Crear directorio para llaveros de APT si no existe en Ubuntu
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755" # rwxr-xr-x
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado

- name: Eza | Añadir clave GPG del repositorio de eza en Ubuntu
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc" # URL oficial de la clave GPG de eza
    dest: "/etc/apt/keyrings/eza-community-keyring.asc" # Nombre descriptivo para la clave
    mode: "0644" # rw-r--r--
  when: ansible_distribution == "Ubuntu"
  register: eza_gpg_key_added # Registrar para la actualización de caché condicional
  # 'become: true' heredado

- name: Eza | Añadir repositorio oficial de eza en Ubuntu
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/eza-community-keyring.asc] http://deb.gierens.de stable main" # URL OFICIAL del repositorio
    state: present
    filename: eza-community # Nombre del archivo .list (ej. /etc/apt/sources.list.d/eza-community.list)
    # No actualizar caché aquí, se hará explícitamente después
  when: ansible_distribution == "Ubuntu"
  register: eza_repo_added # Registrar para la actualización de caché condicional
  # 'become: true' heredado

# Tarea explícita para actualizar la caché de APT DESPUÉS de añadir la clave y el repositorio
# y SOLO si la clave o el repositorio realmente cambiaron (fueron añadidos).
- name: Eza | Actualizar caché de APT después de configurar el repositorio de eza
  ansible.builtin.apt:
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - eza_gpg_key_added.changed or eza_repo_added.changed # Solo si algo relevante cambió
  # 'become: true' heredado
  register: apt_update_after_eza_repo_result # Opcional, para debug

- name: Eza | Mostrar resultado de la actualización de caché (debug opcional)
  ansible.builtin.debug:
    var: apt_update_after_eza_repo_result
  when:
    - ansible_distribution == "Ubuntu"
    - apt_update_after_eza_repo_result is defined
    - apt_update_after_eza_repo_result.changed # Solo mostrar si la caché realmente se actualizó

- name: Eza | Instalar eza en Ubuntu
  ansible.builtin.apt:
    name: eza
    state: present # Asegura que esté instalado
  when: ansible_distribution == "Ubuntu"
  # 'become: true' heredado
  register: eza_install_status

- name: Eza | Mostrar estado de la instalación de eza (debug)
  ansible.builtin.debug:
    var: eza_install_status
  when: ansible_distribution == "Ubuntu"
