---
- name: Añadir repositorio de Fish
  apt_repository:
    repo: ppa:fish-shell/release-4
    state: present
    update_cache: yes

- name: Instalar Fish shell
  apt:
    name: fish
    state: present
    update_cache: yes

- name: Crear directorio de configuración de Fish
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Crear subdirectorios de Fish
  file:
    path: "{{ ansible_env.HOME }}/.config/fish/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop:
    - completions
    - conf.d
    - functions

- name: Instalar dependencias
  apt:
    name: 
      - curl
      - git
      - wget
    state: present

- name: Cambiar shell por defecto a Fish
  shell: chsh -s /usr/bin/fish
  args:
    executable: /bin/bash

- name: Mostrar directorio de configuración
  debug:
    msg: "Directorio de configuración de Fish: {{ playbook_dir }}"

- name: Copiar configuración de Fish
  copy:
    src: "{{ playbook_dir }}/ansible/files/config.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  register: copy_result