---
- name: Install Neovim on Arch Linux
  community.general.pacman:
    name: neovim
    state: present
  become: true

- name: Create Neovim config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
    mode: '0755'

- name: Install Neovim plugins directory
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
    mode: '0755'
