---
- name: Remove Neovim folder
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Install Dependencies
  block:
  - name: Install ninja-build
    ansible.builtin.apt:
      name: ninja-build
      state: present
  - name: Install gettext
    ansible.builtin.apt:
      name: gettext
      state: present
  - name: Install cmake
    ansible.builtin.apt:
      name: cmake
      state: present
  - name: Install unzip
    ansible.builtin.apt:
      name: unzip
      state: present
  - name: Install curl
    ansible.builtin.apt:
      name: curl
      state: present
- name: Clone Neovim Repository
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Build Neovim from source
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim
- name: Install Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
