---
- name: Debug variables en fish.yml
  debug:
    msg:
      - "playbook_dir: {{ playbook_dir }}"
      - "ansible_dir: {{ ansible_dir }}"
      - "inventory_dir: {{ inventory_dir }}"

- name: Debug ansible_env.HOME
  debug:
    msg: "El valor de ansible_env.HOME es: {{ ansible_env.HOME }}"

- name: Añadir repositorio de Fish
  apt_repository:
    repo: ppa:fish-shell/release-4
    state: present
    update_cache: yes
  become: true

- name: Instalar Fish shell
  apt:
    name: fish
    state: present
    update_cache: yes
  become: true

- name: Crear directorio de configuración de Fish
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: '0755'

- name: Crear subdirectorios de Fish
  file:
    path: "{{ ansible_env.HOME }}/.config/fish/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - completions
    - conf.d
    - functions

- name: Debug ruta del archivo config.fish
  debug:
    msg: "Intentando copiar desde: {{ playbook_dir }}/../files/config.fish"

- name: Copiar configuración de Fish
  copy:
    src: "{{ playbook_dir }}/../files/config.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    mode: '0644'
  register: copy_result

- name: Debug resultado de la copia
  debug:
    var: copy_result

- name: Instalar dependencias de Fish
  apt:
    name:
      - curl
      - git
      - wget
      - unzip
    state: present
    update_cache: yes
  become: true

- name: Instalar Fisher (gestor de plugins de Fish)
  shell: fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source; fisher install jorgebucaran/fisher'
  args:
    creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
  become: false

- name: Cambiar shell por defecto a Fish
  shell: chsh -s /usr/bin/fish {{ ansible_env.USER }}
  become: true 