---
- name: FZF | Instalar git (prerrequisito)
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: true

- name: FZF | Clonar o actualizar el repositorio de fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ user_home }}/.fzf"
    depth: 1
    update: yes
  become: true
  become_user: "{{ user_name }}"
  when: ansible_distribution == "Ubuntu"
  register: fzf_clone_result

- name: FZF | Ejecutar el script de instalación de fzf
  ansible.builtin.command:
    cmd: "{{ user_home }}/.fzf/install --all"
    creates: "{{ user_home }}/.fzf/bin/fzf"
  become: true
  become_user: "{{ user_name }}"
  when:
    - ansible_distribution == "Ubuntu"
  environment:
    HOME: "{{ user_home }}"
  register: fzf_install_script_result
  changed_when: "'source {{ user_home }}/.fzf.bash' in fzf_install_script_result.stdout or 'source {{ user_home }}/.fzf.zsh' in fzf_install_script_result.stdout or 'source (fzf --fish)' in fzf_install_script_result.stdout or 'Already installed' not in fzf_install_script_result.stdout"

- name: FZF | Mostrar resultado del script de instalación (debug)
  ansible.builtin.debug:
    var: fzf_install_script_result
  when:
    - ansible_distribution == "Ubuntu"
    - fzf_install_script_result is defined
