---
- name: FZF | Instalar git (prerrequisito para el método de instalación de fzf con git clone)
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: true

- name: FZF | Clonar el repositorio de fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ user_home }}/.fzf"
    depth: 1
  become: true
  become_user: "{{ user_name }}"
  when: ansible_distribution == "Ubuntu"
  register: fzf_clone_result

- name: FZF | Ejecutar el script de instalación de fzf
  ansible.builtin.command:
    cmd: "{{ user_home }}/.fzf/install --all"
    creates: "{{ user_home }}/.fzf/bin/fzf"
  become: true
  become_user: "{{ user_name }}"
  when:
    - ansible_distribution == "Ubuntu"
  register: fzf_install_script_result
  changed_when: "'source' in fzf_install_script_result.stdout or 'Already exists' not in fzf_install_script_result.stdout" # El script de instalación es un poco verboso
