---
# ansible/tasks/fish_ubuntu.yml
# Asume que las variables user_name, user_home, y custom_fish_config_src
# están definidas en el playbook que importa este archivo.
# Asume 'become: true' global o en cada tarea que lo necesite.

- name: Fish | Añadir repositorio de Fish PPA (Ubuntu)
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-4
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Instalar Fish shell (Ubuntu)
  ansible.builtin.apt:
    name: fish
    state: present
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Asegurar que fish está en /etc/shells (Ubuntu)
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/bin/fish
    state: present
    create: yes
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Cambiar shell por defecto a Fish para el usuario {{ user_name }} (Ubuntu)
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /usr/bin/fish
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Crear directorios de configuración de Fish para el usuario (Ubuntu)
  ansible.builtin.file:
    path: "{{ user_home }}/.config/fish/{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  loop:
    - "" # Para .config/fish
    - "conf.d"
    - "completions"
    - "functions"
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Añadir ~/.local/bin al PATH de fish (vía conf.d) (Ubuntu)
  ansible.builtin.copy:
    dest: "{{ user_home }}/.config/fish/conf.d/00_local_bin_path.fish"
    content: |
      # Añadir ~/.local/bin al PATH de fish
      if status is-interactive; or status is-login
        fish_add_path -mP $HOME/.local/bin
      end
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  when: ansible_distribution == "Ubuntu"
  become: true

- name: Fish | Instalar dependencias generales (curl, git, wget) (Ubuntu)
  ansible.builtin.apt:
    name:
      - curl
      - git
      - wget
    state: present
  when: ansible_distribution == "Ubuntu"
  become: true

# Ahora importar las tareas para otras herramientas que podrían modificar config.fish
# o que dependen de la configuración base de fish.
- name: Incluir tareas de Starship
  ansible.builtin.import_tasks: ../starship/main.yml
  when: ansible_distribution == "Ubuntu"

- name: Incluir tareas de Eza
  ansible.builtin.import_tasks: ../eza/main.yml
  when: ansible_distribution == "Ubuntu"

- name: Incluir tareas de Bat
  ansible.builtin.import_tasks: ../bat/main.yml
  when: ansible_distribution == "Ubuntu"

- name: Incluir tareas de Zoxide
  ansible.builtin.import_tasks: ../zoxide/main.yml
  when: ansible_distribution == "Ubuntu"

- name: Incluir tareas de Fzf
  ansible.builtin.import_tasks: ../fzf/main.yml
  when: ansible_distribution == "Ubuntu"

- name: Incluir tareas de The Silver Searcher
  ansible.builtin.import_tasks: ../thesilversearcher/main.yml
  when: ansible_distribution == "Ubuntu"
