---
# ansible/tasks/bat_ubuntu.yml

- name: Bat | Instalar bat (o batcat) en Ubuntu
  ansible.builtin.apt:
    name: bat # El paquete se llama 'bat' en los repositorios de Ubuntu 20.04+
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: true
  register: bat_install_result

- name: Bat | Comprobar si existe /usr/bin/batcat
  ansible.builtin.stat:
    path: /usr/bin/batcat
  when: ansible_distribution == "Ubuntu"
  become: false
  register: batcat_stat

- name: Bat | Comprobar si existe /usr/bin/bat
  ansible.builtin.stat:
    path: /usr/bin/bat
  when: ansible_distribution == "Ubuntu"
  become: false
  register: usr_bin_bat_stat

- name: Bat | Comprobar si existe ~/.local/bin/bat
  ansible.builtin.stat:
    path: "{{ user_home }}/.local/bin/bat"
  when: ansible_distribution == "Ubuntu"
  become: false
  register: local_bin_bat_stat

- name: Bat | Determinar si el enlace simbólico para 'bat' en ~/.local/bin es necesario
  ansible.builtin.set_fact:
    create_bat_symlink_in_local_bin: >-
      {# Condición 1: /usr/bin/batcat debe existir #}
      {% if batcat_stat.stat.exists %}
        {# Condición 2: /usr/bin/bat NO debe ser ya un enlace funcional a batcat #}
        {% if not (usr_bin_bat_stat.stat.exists and usr_bin_bat_stat.stat.islnk and usr_bin_bat_stat.stat.lnk_target == '/usr/bin/batcat') %}
          {# Condición 3: ~/.local/bin/bat NO debe ser ya un enlace funcional a batcat #}
          {% if not (local_bin_bat_stat.stat.exists and local_bin_bat_stat.stat.islnk and local_bin_bat_stat.stat.lnk_target == '/usr/bin/batcat') %}
            true
          {% else %}
            false
          {% endif %}
        {% else %}
          false
        {% endif %}
      {% else %}
        false
      {% endif %}
  when: ansible_distribution == "Ubuntu"

- name: Bat | Crear directorio ~/.local/bin para el usuario si no existe (y es necesario para el enlace)
  ansible.builtin.file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  when:
    - ansible_distribution == "Ubuntu"
    - create_bat_symlink_in_local_bin | default(false)
  become: true

- name: Bat | Crear enlace simbólico bat -> batcat en ~/.local/bin (si es necesario)
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ user_home }}/.local/bin/bat"
    owner: "{{ user_name }}" # Propietario correcto
    group: "{{ user_name }}" # Grupo correcto
    state: link
    force: yes
  when:
    - ansible_distribution == "Ubuntu"
    - create_bat_symlink_in_local_bin | default(false)
  become: true

- name: Bat | Mostrar estado de la instalación (debug)
  ansible.builtin.debug:
    var: bat_install_result
  when:
    - ansible_distribution == "Ubuntu"
    - bat_install_result is defined
